steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/inspiring-grove-344016/elijah-awesome:$COMMIT_SHA ', '.']
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/inspiring-grove-344016/elijah-awesome:$COMMIT_SHA ']
