steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/inspiring-grove-344016/elijah-awesome:978ef843bc991243ef295dbc18bd6f4a9358a323', '.']
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/inspiring-grove-344016/elijah-awesome:978ef843bc991243ef295dbc18bd6f4a9358a323']
