steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/inspiring-grove-344016/elijah-awesome:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/inspiring-grove-344016/elijah-awesome:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'inspiring-grove-344016', '--region=europe-west1', '--platform=managed', '--image=gcr.io/inspiring-grove-344016/elijah-awesome:$SHORT_SHA']

